name: "Update flakes"
on:
  schedule:
  - cron: "0 23 * * *"
  - workflow_dispatch:  # click the button on Github repo!
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: Flake update
